#!/usr/bin/perl

$i = 0;
$current_normal = 0.33;
$current_lpm    = 0.0011;
$current_tx     = 17.4;
$current_rx     = 18.8;
$voltage        = 3.0;
$ticks_per_sec  = 32768.0;
$mah            = 2300.0;
$msg="";
$total_energy_consumption=0.0;
$total_lpm_consumption=0.0;

while(<>) {
    if(/P (\d+) (\d+) (\d+) (\d+) (\d+) (\d+) (\d+) (\d+)/) {
        $all_cpu[$i] = (($5)*$current_normal*$voltage)/$ticks_per_sec;
        $all_lpm[$i] = (($6)*$current_lpm*$voltage)/$ticks_per_sec;
        $all_tx[$i] = (($7)*$current_tx*$voltage)/$ticks_per_sec;
        $all_rx[$i] = (($8)*$current_rx*$voltage)/$ticks_per_sec;
        $row_tot[$i]  = $all_cpu[$i]+$all_lpm[$i]+$all_tx[$i]+$all_rx[$i];
        
            $all_tx_per[$i] = $7 / ($5+$6+$7+$8);
            $all_rx_per[$i] = $8 / ($5+$6+$7+$8);
            $all_cpu_per[$i]= $5/ ($5+$6+$7+$8);
            $all_lpm_per[$i]= $6/ ($5+$6+$7+$8);
            
            $index = $i*10.0/60.0;
            print $index." ".$all_cpu[$i]." ".$all_lpm[$i]." ".$all_tx[$i]." ".$all_rx[$i]." ".$row_tot[$i]." ".$all_tx_per[$i].
            " ".$all_rx_per[$i]." ". $all_cpu_per[$i]." ".$all_lpm_per[$i]." ".$msg."\n";
            $msg="";
        
            #Overall energy consumption counter
            $total_energy_consumption+=$row_tot[$i];

            #LPM energy consumption counter
            $total_lpm_consumption+=$all_lpm[$i];
        $i+=1;
    }
    elsif (/WORK_START/){
        $msg.="wB-";
    }
    elsif (/STOP_WORK/){
        $msg.="wE-";
    }
    elsif (/START_OBSERVE/){
        $msg.="oB-";
    }
    elsif (/STOP_OBSERVE/){
        $msg.="oE-";
    }
    
}
$total_energy_consumption = ($mah*$voltage)/($total_energy_consumption);
$total_lpm_consumption= $total_lpm_consumption/$i;
print $total_energy_consumption." ".$total_lpm_consumption."\n";